# TF-IDF

We'll rely on term frequency times inverted document frequency to measure meaningful similarity between documents. Let's start by generating a matrix for the separate constituent parts of _Stjórn_.

## TODO

Go back to the generate-scripts and filter out accented vowels as well as eth

In [ ]:
import os,glob,json
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
#from unidecode import unidecode

In [ ]:
titles = ['prologue', 'introduction', 'gn', 'ex', 'lv', 'nm', 'dt', 'ios', 'idc', 'rt', '1sm', '2sm', '3rg', '4rg']
tokens = []
for title in titles:
    with open(f"nlp/{title}.txt") as raw:
        document = raw.read().replace('\n', ' ')
        tokens.extend(document.split())

work_indices = {
    'stjorn1': (650,124417),
    'stjorn2': (124417,147678),
    'stjorn3': (147678,156943,160719),
    'stjorn4': (156943,160719)
}

stjorn = dict()
for _work, _range in work_indices.items():
    if len(_range) == 2:
        stjorn[_work] = ' '.join(tokens[_range[0]:_range[1]])
    else:
        stjorn[_work] = ' '.join(tokens[_range[0]:_range[1]] + tokens[_range[2]:])

menota = dict()
for text in glob.glob('../menota/dipl/*txt'):
    ref = os.path.basename(text).replace('.txt', '')
    with open(text) as doc:
        menota[ref] = doc.read().replace('\n', '')

In [8]:
vectorizer = TfidfVectorizer(min_df=1)
model = vectorizer.fit_transform(stjorn.values())
df = pd.DataFrame(cosine_similarity(model), stjorn.keys(), stjorn.keys())
df

          stjorn1   stjorn2   stjorn3   stjorn4
stjorn1  1.000000  0.811713  0.508459  0.842683
stjorn2  0.811713  1.000000  0.394915  0.833537
stjorn3  0.508459  0.394915  1.000000  0.469750
stjorn4  0.842683  0.833537  0.469750  1.000000

This tells us _Stjórn III_ is the most distinct of the three. Remarkably, compared to _Stjórn IV_, which covers some of the same ground, it is the least similar constituent text. Perhaps further analysis can tell us how.

First let's add _Konungs skuggsjá_ from Menota, as well as Unger's own edition of the _Norwegian Homily Book_. Fingers crossed that we have got the normalization standard of the former to approach Unger's methods reasonably well.

In [9]:
nhb_titles = ['alcuin', 'hom', 'olafr', 'visio', 'paternoster', 'anhang1'] # this is the sequence matched in Menota
nhb = ''
for title in nhb_titles:
    filepath = f'../nhb/nlp/{title}.txt'
    with open(filepath) as doc:
        nhb = nhb + doc.read().replace('\n', '')
stjorn_plus = []
for v in stjorn.values():
    stjorn_plus.append(v)
stjorn_plus.extend([menota['nks235g_konungs_skuggsja'], nhb])
model = vectorizer.fit_transform(stjorn_plus)
df = pd.DataFrame(cosine_similarity(model), list(stjorn.keys()) + ['ks', 'nhb'], list(stjorn.keys()) + ['ks', 'nhb'])
df

          stjorn1   stjorn2   stjorn3   stjorn4        ks       nhb
stjorn1  1.000000  0.786055  0.523931  0.812032  0.242538  0.385928
stjorn2  0.786055  1.000000  0.402580  0.797535  0.228309  0.329922
stjorn3  0.523931  0.402580  1.000000  0.474961  0.696934  0.827073
stjorn4  0.812032  0.797535  0.474961  1.000000  0.244245  0.385029
ks       0.242538  0.228309  0.696934  0.244245  1.000000  0.710246
nhb      0.385928  0.329922  0.827073  0.385029  0.710246  1.000000

Next, let's model all of Menota along with Stjórn. Perhaps we'll leave Unger's _Homily Book_ in alongside the Menota edition, just for comparison's sake.

In [ ]:
corpus = []
titles = []
for k,v in stjorn.items():
    titles.append(k)
    corpus.append(v)
titles.append('nhb')
corpus.append(nhb)
for k,v in menota.items():
    titles.append(k)
    corpus.append(v)
model = vectorizer.fit_transform(corpus)
df = pd.DataFrame(cosine_similarity(model), titles, titles)
df

,stjorn1,stjorn2,stjorn3,stjorn4,nhb,am132_egils_saga,am162btheta_njals_saga,holmPerg30_langslog,am1056IX_konungs_skuggsja_fragment,am78_kristinrettir,...,am132_hallfredar_saga,am35_heimskringla1,am242_codex_wormianus,dg8II_olafs_saga,am28_codex_runicus,holmPerg34_boejarlog,dg8I_landslog,nraNorrFragm55A_hakonar_saga,nraNorrFragm52_olafs_saga_helga_hin_elzta,holmPerg6_barlaams_saga
stjorn1,1.000000,0.748352,0.463369,0.716519,0.321304,0.729321,0.285188,0.450608,0.460412,0.185049,...,0.638843,0.263255,0.772092,0.240468,0.308482,0.599206,0.555753,0.419250,0.203710,0.256146
stjorn2,0.748352,1.000000,0.367732,0.690449,0.278872,0.683951,0.228120,0.471444,0.422574,0.194668,...,0.615179,0.228013,0.700719,0.225097,0.278706,0.635361,0.551214,0.362248,0.188396,0.242982
stjorn3,0.463369,0.367732,1.000000,0.422768,0.804556,0.423967,0.735041,0.264177,0.232953,0.575662,...,0.358496,0.747495,0.434986,0.755522,0.118952,0.330666,0.343903,0.557097,0.643045,0.816467
stjorn4,0.716519,0.690449,0.422768,1.000000,0.305745,0.627295,0.264138,0.405317,0.363065,0.182923,...,0.537848,0.241138,0.637794,0.219982,0.242823,0.509276,0.477872,0.374106,0.188195,0.214269
nhb,0.321304,0.278872,0.804556,0.305745,1.000000,0.354436,0.653088,0.338534,0.236618,0.671409,...,0.277612,0.702398,0.406509,0.788540,0.084950,0.371127,0.402062,0.437926,0.642324,0.815319
am132_egils_saga,0.729321,0.683951,0.423967,0.627295,0.354436,1.000000,0.351140,0.504718,0.443000,0.262330,...,0.758933,0.378394,0.782320,0.353706,0.276509,0.682695,0.589778,0.548603,0.297073,0.318854
am162btheta_njals_saga,0.285188,0.228120,0.735041,0.264138,0.653088,0.351140,1.000000,0.176453,0.141569,0.474757,...,0.295919,0.660115,0.285784,0.647034,0.071623,0.271676,0.212355,0.469486,0.583432,0.701552
holmPerg30_langslog,0.450608,0.471444,0.264177,0.405317,0.338534,0.504718,0.176453,1.000000,0.353913,0.472909,...,0.423559,0.211825,0.558766,0.300529,0.309754,0.535706,0.627539,0.262156,0.179076,0.236361
am1056IX_konungs_skuggsja_fragment,0.460412,0.422574,0.232953,0.363065,0.236618,0.443000,0.141569,0.353913,1.000000,0.191966,...,0.383130,0.168137,0.519105,0.182938,0.172372,0.439638,0.395357,0.207105,0.152221,0.187431
am78_kristinrettir,0.185049,0.194668,0.575662,0.182923,0.671409,0.262330,0.474757,0.472909,0.191966,1.000000,...,0.197786,0.553633,0.313521,0.656271,0.188478,0.391393,0.602870,0.349404,0.510014,0.654574
am63_heimskringla3,0.273708,0.234338,0.735079,0.252718,0.680642,0.373788,0.646999,0.215270,0.177714,0.532394,...,0.285179,0.941141,0.365781,0.774729,0.070420,0.314863,0.257117,0.544648,0.703217,0.785613
dg4-7_strengleikar,0.264076,0.212417,0.819889,0.218777,0.799052,0.336597,0.697447,0.221838,0.173574,0.626974,...,0.271462,0.804838,0.316898,0.852748,0.071742,0.292356,0.272614,0.523177,0.721156,0.901317
am132_droplaugasona_saga,0.665099,0.640855,0.337100,0.568581,0.270289,0.802042,0.290332,0.447938,0.397594,0.197528,...,0.694934,0.289886,0.692006,0.279855,0.261524,0.599327,0.521402,0.443690,0.224541,0.246811
am132_kormaks_saga,0.560652,0.535829,0.294350,0.468552,0.238642,0.663701,0.247710,0.380594,0.337211,0.176709,...,0.601051,0.237803,0.593786,0.241269,0.217680,0.507808,0.442220,0.356363,0.198335,0.216014
nraNorrFragm53_haralds_saga_hardrada,0.468344,0.436430,0.269418,0.400063,0.176410,0.588973,0.197521,0.308454,0.276740,0.133696,...,0.484901,0.262094,0.495499,0.214149,0.185658,0.393334,0.346081,0.410373,0.176659,0.173234
am132_finnboga_saga,0.660071,0.605030,0.354904,0.532430,0.282254,0.750041,0.287406,0.422374,0.402666,0.188775,...,0.663223,0.284498,0.673077,0.282738,0.244604,0.574253,0.496402,0.411786,0.231028,0.257766
am132_fostbraedra_saga,0.695973,0.652222,0.373207,0.581697,0.307613,0.817858,0.323714,0.455656,0.412657,0.224388,...,0.704735,0.318605,0.724764,0.306179,0.259400,0.627773,0.540164,0.455284,0.254335,0.280264
lbsFragm82_olafs_saga_helga,0.225799,0.192477,0.561057,0.204342,0.525101,0.331492,0.495742,0.174813,0.154602,0.412588,...,0.251048,0.641453,0.312733,0.574751,0.055153,0.258333,0.215318,0.416261,0.688420,0.600817
am619_norwegian_homily_book,0.672364,0.646777,0.414823,0.577061,0.557288,0.729581,0.280562,0.573570,0.460956,0.384225,...,0.617699,0.360380,0.798616,0.442241,0.254279,0.680405,0.673954,0.399345,0.321642,0.379692
am56_landslog,0.217732,0.222568,0.580016,0.212053,0.679406,0.283335,0.470548,0.484989,0.213804,0.938788,...,0.215540,0.550732,0.350025,0.658636,0.177854,0.428761,0.655360,0.335309,0.500607,0.643195
holmPerg17_thomass_saga,0.624829,0.443717,0.579391,0.433252,0.558941,0.555889,0.423280,0.420463,0.356797,0.425852,...,0.477087,0.464194,0.584440,0.552656,0.184901,0.493984,0.500212,0.438441,0.415628,0.516093
am383I_thorlaks_saga,0.215162,0.174099,0.448595,0.151745,0.425127,0.299549,0.412271,0.148169,0.135189,0.328929,...,0.241521,0.492452,0.243982,0.498699,0.160910,0.270358,0.208119,0.428242,0.438993,0.493991
holmPerg4_thidreks_saga,0.288862,0.269812,0.828474,0.255260,0.791857,0.364479,0.704747,0.289194,0.201736,0.673120,...,0.299257,0.792454,0.366015,0.844223,0.102839,0.350346,0.342118,0.538568,0.723743,0.890654
am132_njals_saga,0.744594,0.706287,0.415510,0.623284,0.330454,0.868419,0.397351,0.494212,0.444907,0.233294,...,0.772318,0.331205,0.762447,0.325332,0.286796,0.665125,0.573802,0.484276,0.263436,0.299424
am36_heimskringla2,0.309130,0.265313,0.758734,0.280762,0.708921,0.417260,0.667109,0.247139,0.204747,0.548897,...,0.323569,0.959186,0.408179,0.804254,0.083520,0.355105,0.293215,0.558525,0.728190,0.806114
am544_voluspa,0.405335,0.382553,0.189421,0.341339,0.142487,0.395744,0.121782,0.260456,0.242146,0.109830,...,0.344797,0.155249,0.468797,0.135334,0.168094,0.316921,0.292462,0.209205,0.107561,0.113639
am162bkappa_njals_saga,0.262443,0.226391,0.664056,0.237505,0.616800,0.373490,0.637280,0.205120,0.151792,0.474398,...,0.305654,0.637379,0.300085,0.633943,0.073323,0.293485,0.233357,0.469708,0.550969,0.677072
am305_landslog,0.197563,0.202864,0.544162,0.177795,0.624502,0.266508,0.451438,0.422758,0.199430,0.898807,...,0.202014,0.545250,0.309328,0.619800,0.145690,0.389454,0.605706,0.329477,0.495004,0.635161
am132_olkofra_thattr,0.572001,0.558609,0.392927,0.502303,0.354118,0.725621,0.342388,0.427427,0.359945,0.266965,...,0.634613,0.329022,0.636934,0.333286,0.209389,0.572692,0.495892,0.402422,0.269204,0.313357
nraNorrFragm54_sverris_saga,0.352587,0.328450,0.790717,0.337657,0.715487,0.421107,0.677865,0.259286,0.216465,0.557261,...,0.338342,0.741007,0.410805,0.714367,0.103551,0.338933,0.299182,0.568828,0.644089,0.776161
nraNorrFragm55B_hakonar_saga,0.190760,0.193694,0.550567,0.189691,0.525408,0.333634,0.488229,0.193903,0.125522,0.446689,...,0.246022,0.584181,0.258658,0.578805,0.060216,0.268942,0.218741,0.472711,0.503019,0.604888
gks2365_voluspa,0.128820,0.117150,0.413245,0.130597,0.403516,0.170211,0.353480,0.120667,0.092747,0.335455,...,0.127960,0.449635,0.213106,0.409589,0.030891,0.149762,0.138960,0.263964,0.417607,0.452733
am243balpha_konungs_skuggsja,0.275549,0.237192,0.686689,0.246953,0.702271,0.336141,0.568777,0.433107,0.212330,0.555413,...,0.262288,0.641115,0.359992,0.702010,0.083218,0.339977,0.351643,0.410667,0.583613,0.716711
nraNorrFragm51_fagrskinna,0.119370,0.118224,0.491174,0.108107,0.497126,0.178887,0.430107,0.123046,0.102039,0.395101,...,0.138250,0.546902,0.179427,0.575648,0.033317,0.176629,0.149435,0.318321,0.474155,0.575941
am132_viga-glums_saga,0.726521,0.685721,0.401977,0.593601,0.342153,0.851489,0.344646,0.491019,0.446071,0.246680,...,0.759712,0.328334,0.759904,0.337124,0.273307,0.671270,0.583920,0.457588,0.269943,0.303787
am279a_gragas,0.226857,0.204265,0.450052,0.237548,0.474085,0.308034,0.398508,0.257913,0.165530,0.399565,...,0.231455,0.440351,0.312501,0.434429,0.054448,0.340994,0.293326,0.317076,0.418257,0.453558
am677_gregory,0.531046,0.508069,0.340567,0.442464,0.349632,0.584013,0.270911,0.373602,0.338265,0.243066,...,0.493490,0.356905,0.592118,0.320535,0.197020,0.537039,0.461676,0.355618,0.352760,0.323342
am132_laxdoela_saga,0.721918,0.680016,0.416909,0.599534,0.347098,0.878692,0.348495,0.493339,0.439744,0.254020,...,0.764185,0.354707,0.769278,0.354585,0.267713,0.655730,0.574340,0.488173,0.286947,0.312724
am302_landslog,0.193953,0.200113,0.534692,0.179736,0.613409,0.267735,0.447552,0.449743,0.192408,0.924420,...,0.200727,0.531590,0.308771,0.600407,0.171443,0.396748,0.607426,0.326108,0.483291,0.623121
am178_thidreks_saga,0.165463,0.183253,0.149867,0.146953,0.131937,0.196551,0.109155,0.122172,0.112988,0.089646,...,0.164049,0.134507,0.220396,0.130150,0.041841,0.194555,0.156056,0.117118,0.109416,0.120046
am132_bandamanna_saga,0.675692,0.647547,0.398944,0.554554,0.354468,0.791321,0.333863,0.484267,0.432757,0.256670,...,0.698354,0.304622,0.733683,0.322479,0.247939,0.625872,0.558705,0.394985,0.263299,0.304889
am655_laeknisbok,0.147910,0.139526,0.543393,0.131972,0.540970,0.196946,0.466771,0.142542,0.134531,0.462260,...,0.157439,0.591895,0.250279,0.572521,0.025609,0.205218,0.177090,0.336099,0.543549,0.621297
am519a_alexanders_saga,0.525073,0.535123,0.331151,0.463833,0.333824,0.576051,0.227237,0.393534,0.359435,0.271640,...,0.483259,0.313304,0.630958,0.305392,0.188813,0.563071,0.502535,0.341166,0.298056,0.327564
holmPerg34_landslog,0.624790,0.653535,0.370103,0.527165,0.421443,0.699271,0.296892,0.579911,0.465780,0.423598,...,0.588707,0.352371,0.730515,0.386179,0.238749,0.940315,0.716953,0.378441,0.310193,0.373033
am162balpha_njals_saga,0.613095,0.584767,0.345557,0.529579,0.253685,0.579290,0.278453,0.355852,0.349766,0.122578,...,0.515929,0.205272,0.580919,0.198570,0.237435,0.480515,0.423687,0.311797,0.163150,0.186921
am113_islendingabok,0.171652,0.135629,0.448123,0.146581,0.443741,0.251982,0.409915,0.139385,0.106944,0.351601,...,0.189943,0.510243,0.223037,0.462425,0.052889,0.225859,0.183832,0.338713,0.464328,0.485250
nraNorrFragm7_landslog,0.239980,0.240224,0.573009,0.225053,0.653702,0.327778,0.459714,0.438583,0.220949,0.787918,...,0.252739,0.544898,0.373222,0.635420,0.089877,0.434900,0.690367,0.339371,0.503782,0.616622
nks235g_konungs_skuggsja,0.190201,0.186604,0.660723,0.171812,0.665723,0.237652,0.566643,0.200999,0.159639,0.571798,...,0.179663,0.669613,0.274769,0.697407,0.052309,0.289964,0.248614,0.400434,0.607505,0.769874
am132_hallfredar_saga,0.638843,0.615179,0.358496,0.537848,0.277612,0.758933,0.295919,0.423559,0.383130,0.197786,...,1.000000,0.284827,0.666277,0.282423,0.241928,0.575418,0.494543,0.435543,0.229443,0.253193
am35_heimskringla1,0.263255,0.228013,0.747495,0.241138,0.702398,0.378394,0.660115,0.211825,0.168137,0.553633,...,0.284827,1.000000,0.349456,0.807477,0.072021,0.312734,0.258079,0.563383,0.719072,0.807480
am242_codex_wormianus,0.772092,0.700719,0.434986,0.637794,0.406509,0.782320,0.285784,0.558766,0.519105,0.313521,...,0.666277,0.349456,1.000000,0.343782,0.276112,0.690539,0.648305,0.413927,0.290779,0.320064
dg8II_olafs_saga,0.240468,0.225097,0.755522,0.219982,0.788540,0.353706,0.647034,0.300529,0.182938,0.656271,...,0.282423,0.807477,0.343782,1.000000,0.081211,0.349731,0.360348,0.497847,0.686054,0.845785
am28_codex_runicus,0.308482,0.278706,0.118952,0.242823,0.084950,0.276509,0.071623,0.309754,0.172372,0.188478,...,0.241928,0.072021,0.276112,0.081211,1.000000,0.238481,0.282922,0.225532,0.044559,0.063987
holmPerg34_boejarlog,0.599206,0.635361,0.330666,0.509276,0.371127,0.682695,0.271676,0.535706,0.439638,0.391393,...,0.575418,0.312734,0.690539,0.349731,0.238481,1.000000,0.675936,0.369602,0.283471,0.334291
dg8I_landslog,0.555753,0.551214,0.343903,0.477872,0.402062,0.589778,0.212355,0.627539,0.395357,0.602870,...,0.494543,0.258079,0.648305,0.360348,0.282922,0.675936,1.000000,0.303350,0.232177,0.285317
nraNorrFragm55A_hakonar_saga,0.419250,0.362248,0.557097,0.374106,0.437926,0.548603,0.469486,0.262156,0.207105,0.349404,...,0.435543,0.563383,0.413927,0.497847,0.225532,0.369602,0.303350,1.000000,0.438936,0.492989
nraNorrFragm52_olafs_saga_helga_hin_elzta,0.203710,0.188396,0.643045,0.188195,0.642324,0.297073,0.583432,0.179076,0.152221,0.510014,...,0.229443,0.719072,0.290779,0.686054,0.044559,0.283471,0.232177,0.438936,1.000000,0.738649
holmPerg6_barlaams_saga,0.256146,0.242982,0.816467,0.214269,0.815319,0.318854,0.701552,0.236361,0.187431,0.654574,...,0.253193,0.807480,0.320064,0.845785,0.063987,0.334291,0.285317,0.492989,0.738649,1.000000

That's not a good sign, two editions of the _Norwegian Homily Book_ doing no better than `0.54` similarity... If I run `unidecode` (which strips out accented vowels, among other things), it only gets up to `0.55`.